#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar & hyprpaper 
exec-once = setxkbmap -option caps:escape
# exec-once = hyprpaper
exec-once = swww-daemon &
# exec-once = sleep 2 && obsidian
# exec-once = de.shorsh.discord-screenaudio
# exec-once = steam

exec-once = sleep 1 && hyprctl dispatch moveworkspacetomonitor 1 eDP-1
exec-once = sleep 1 && hyprctl dispatch moveworkspacetomonitor 2 DP-3
exec-once = sleep 1 && hyprctl dispatch moveworkspacetomonitor 3 HDMI-A-1
