preload = /home/jason/Pictures/wallpapers/northbg.png

wallpaper {
  monitor = eDP-1
  path = /home/jason/Pictures/wallpapers/northbg.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = /home/jason/Pictures/wallpapers/northbg.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/jason/Pictures/wallpapers/northbg.png
  fit_mode = cover
}

# Fallback
wallpaper {
  monitor =
  path = /home/jason/Pictures/wallpapers/northbg.png
  fit_mode = cover
}
