#############
### Rules ###
#############

# windowrulev2 = workspace 2, class:^(firefox)$
# windowrulev2 = workspace 3, class:^(obsidian)$
# windowrulev2 = workspace 5, class:^(de.shorsh.discord-screenaudio)$
# windowrulev2 = workspace 4, class:^(steam)$
# Weniger Effekte für Unity
# windowrulev2 = float, class:^(Unity)$
# windowrulev2 = noblur, class:^(Unity)$
# windowrulev2 = nofocus, class:^(Unity)$
# windowrulev2 = noinitialfocus, class:^(Unity)$
# windowrulev2 = opaque, class:^(Unity)$
#
# windowrulev2 = float,class:^(UnityEditor)$
# windowrulev2 = tile,class:^(UnityHub)$

windowrule = float class:^(pavucontrol)$
windowrule = float class:^(blueman-manager)$

 windowrule = opacity 0.92 : class:^(Rofi)$
windowrule = opacity 0.92 : class:^(wlogout)$
windowrule = opacity 0.85 : class:^(Pavucontrol)$
windowrule = opacity 0.88 : class:^(blueman-manager)$

# Terminal immer leicht transparent
windowrule = opacity 0.90 : class:^(Alacritty)$


# Conky unter Wayland als XWayland-Client
windowrule = no_anim : class:^(conky)$
windowrule = opacity 0.90 : class:^(conky)$
windowrule = no_focus : class:^(conky)$
# windowrulev2 = nofullscreenrequest,class:^(conky)$
windowrule = no_shadow : class:^(conky)$
# windowrulev2 = layerrule animation default,class:^(conky)$
# windowrulev2 = layerrule background,class:^(conky)$
# windowrule = float,class:^(conky)$


# Conky: unterster Layer, keine Interaktionsprobleme
windowrule = no_focus : class:^(conky)$
windowrule = no_anim : class:^(conky)$
windowrule = no_shadow : class:^(conky)$
# windowrule = nofullscreenrequest,class:^(conky)$
# windowrulev2 = float,class:^(conky)$
# windowrule = layerrule bottom : class:^(conky)$

# Floating default design
# windowrulev2 = rounding 20
# windowrulev2 = opacity 0.92
# windowrulev2 = border 2

layerrule = blur : logout_dialog

# swaync
layerrule = blur swaync-control-center
layerrule = blur swaync-notification-window
# sleep 1 && hyprctl dispatch moveworkspacetomonitor 1 eDP-1
# sleep 1 && hyprctl dispatch moveworkspacetomonitor 2 DP-3
# sleep 1 && hyprctl dispatch moveworkspacetomonitor 3 HDMI-A-1
