source = ~/.config/hypr/themes/matugen.conf

$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = $inverse_on_surface
    # inner_color = rgba(15,15,15,0.9) # Hintergrund wie Alacritty background, mit Opazität
    outer_color = rgba(ff6a00) rgba(ff8a33) 120deg # Orange Verlauf wie Akzentfarben
    check_color = rgba(f2f2f2ee) rgba(ffb366ee) 120deg # Weiß zu softer Orange für Erfolg
    fail_color = rgba(ff6a00) rgba(ff8a33) 20deg # Orange Akzent als Fehlerfarbe
    font_color = rgb(242,242,242) # foreground
    
    fade_on_empty = false
    rounding = 100

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.2

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -380
    halign = center
    valign = center
}

# TIME (Hours)
label {
    monitor =
    text = cmd[update:60000] date +"%H" # update every 60 seconds
    font_size = 150
    font_family = "Iosevka Nerd Font Mono"
    # font_family = $font
    position = 0, -330
    halign = center
    valign = top
    color = $primary
}

# TIME (Minutes) 
label {
    monitor =
    text = cmd[update:60000] date +"%M" # update every 60 seconds
    font_size = 150
    font_family = "Iosevka Nerd Font Mono"
    # font_family = $font
    position = 0, -500
    halign = center
    valign = top
}


label {
  text = •
  color = rgb(ff6a00)
  font_size = 25
    position = -260, -1020
    halign = right
    valign = top
}

# DATE
label {
    monitor =
 
    text = cmd[update:60000] date +" %A   %d %B %Y"
    font_size = 25
    # font_family = Iosevka Nerd Font Mono
    # color = rgba(ff6a00,0.92) # Akzentfarbe wie tmux
    color = $on_surface # Akzentfarbe wie tmux
    shadow = true
    shadow_color = rgba(0,0,0,0.35)
    shadow_offset = 0,2
    position = -30, -1020
    halign = right
    valign = top
}
# label {
#     monitor =
#     text = $LAYOUT[en,ru]
#     font_size = 24
#     onclick = hyprctl switchxkblayout all next
#
#     position = 250, -20
#     halign = center
#     valign = center
# }
